baseURL = "https://wantflying.github.io/blog"
defaultContentLanguage = "zh"
languageCode = "zh-Hans"
title = "yuan's Blog"
theme = "dream"

enableGitInfo = true
enableRobotsTXT = true

hasCJKLanguage = true

[services]
  [services.disqus]
    shortname = 'wantflying-github-io'
# [services.googleAnalytics]
# ID = "G-K6V0YY3HWS"

[markup]
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
noClasses = false

[params]
lightTheme = "emerald"
darkTheme = "forest"

# backgroundImage = "me/background.jpg"
# backgroundImageDark = ""

images = ["me/background.jpg"]

author = "wantflying"
description = "The life record of yuan is presented here."
avatar = "me/yy.jpg"
headerTitle = "yuan' Blog"
motto = "命运早已注定,你我都是牛马。"

# footerBottomText = ""

rss = false

# utterancesRepo = "yuan/yuan.github.io"

# valine = true
# LEANCLOUD_APP_ID = ""
# LEANCLOUD_APP_KEY = ""
# VALINE_LANGUAGE = ""

email = "xiushengyuan@gmail.com"

siteStartYear = 2020

favicon = "favicon.ico"

# Syntax highlighting
customSyntaxHighlighting = true

# options
stickyNav = true
# reorderNavItems = ["search", "rss", "posts", "categories", "tags"]
collapseNavItems = ["posts", "categories", "tags"]
showTableOfContents = true
showSummaryCoverInPost = true
showPrevNextPost = true
# hasTwitterEmbed = true

[params.navItems]

[params.advanced]
customCSS = ["css/custom.css"]
# customJS = []
[params.busuanzi]
enable = true
[params.experimental]
jsDate = true
jsDateFormat = "yyyy年MM月dd日"
# jsDateFormat = "yyyy年MM月dd日，cccc"
